name: Apply Terraform 
env:
    AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
    AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}


on:
    push:
        branches:
            main
jobs:
    apply:
        runs-on: ubuntu-latest
       

        steps:
           - name: Checkout 
             uses: actions/checkout@v2

           - name: Install Terraform
             uses: hashicorp/setup-terraform@v2
             with:
                terraform_version: latest 

           - name: Terraform Init
             run: terraform init -input=false

           - name: Apply Terraform 
             run: terraform apply -auto-approve -input=false
        
